{
  "name": "AssertException",
  "comment": "AssertException is used in situations that the programmer believes can\u0027t happen.\n If it does, then there is a programming error of some kind.",
  "javadoc": "\u003ccode\u003eAssertException\u003c/code\u003e is used in situations that the programmer believes can\u0027t happen.\n If it does, then there is a programming error of some kind.",
  "static": false,
  "implements": [],
  "extends": "java.lang.RuntimeException",
  "fields": [],
  "methods": [
    {
      "name": "\u003cinit\u003e",
      "comment": "Create a new AssertException with no message.",
      "javadoc": "Create a new AssertException with no message.",
      "static": false,
      "params": [],
      "return": {
        "type_long": "void",
        "type_short": "void",
        "comment": ""
      },
      "throws": []
    },
    {
      "name": "\u003cinit\u003e",
      "comment": "Create a new AssertException with the given message.",
      "javadoc": "Create a new AssertException with the given message.\n@param msg the exception message.",
      "static": false,
      "params": [
        {
          "name": "msg",
          "type_long": "java.lang.String",
          "type_short": "String",
          "comment": "the exception message."
        }
      ],
      "return": {
        "type_long": "void",
        "type_short": "void",
        "comment": ""
      },
      "throws": []
    },
    {
      "name": "\u003cinit\u003e",
      "comment": "Create a new AssertException using another exception (Throwable) has occurred.\n The message for this exception will be derived from the Throwable.",
      "javadoc": "Create a new AssertException using another exception (Throwable) has occurred.\n The message for this exception will be derived from the Throwable.\n@param t the Throwable which caused this exception to be generated.",
      "static": false,
      "params": [
        {
          "name": "t",
          "type_long": "java.lang.Throwable",
          "type_short": "Throwable",
          "comment": "the Throwable which caused this exception to be generated."
        }
      ],
      "return": {
        "type_long": "void",
        "type_short": "void",
        "comment": ""
      },
      "throws": []
    },
    {
      "name": "\u003cinit\u003e",
      "comment": "Create a new AssertException with the given message.",
      "javadoc": "Create a new AssertException with the given message.\n@param message the exception message.\n@param throwable the Throwable which caused this exception to be generated.",
      "static": false,
      "params": [
        {
          "name": "message",
          "type_long": "java.lang.String",
          "type_short": "String",
          "comment": "the exception message."
        },
        {
          "name": "throwable",
          "type_long": "java.lang.Throwable",
          "type_short": "Throwable",
          "comment": "the Throwable which caused this exception to be generated."
        }
      ],
      "return": {
        "type_long": "void",
        "type_short": "void",
        "comment": ""
      },
      "throws": []
    }
  ]
}
